name: Deploy

on:
  push:
    branches:
      - "master"
jobs:
  deploy:
    run-on: ubuntu-20.04
   concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
    steps:
      - uses: actions/checkout@v3
      - name: Build
        runs-on: ${{ matrix.os }}
        steps:
          - uses: actions/checkout@v2
          - uses: actions/setup-node@v2
            with:
              node-version: ${{ matrix.node-version }}
          - run: node --version
          - run: yarn install
          - run: yarn build
          - run: yarn lint
          - run: yarn ts-node ./.github/check_nodiff.ts
      - name: Deploy
          uses: peaceiris/actions-gh-pages@v3
          if: ${{ github.ref == 'refs/heads/master' }}
          with:
            github_token: ${{ secrets.GITHUB_TOKEN }}
            publish_dir: ./public

