name: Deploy

on:
  push:
    branches: [ master ]
jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest]
        node-version: [16]
    name: Build
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
      - run: node --version
      - run: yarn install
      - run: yarn build
      - name: Deploy
          uses: peaceiris/actions-gh-pages@v3
          if: ${{ github.ref == 'refs/heads/master' }}
          with:
            github_token: ${{ secrets.GITHUB_TOKEN }}
            publish_dir: ./public

